//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public message()
        {
            this.units = new HashSet<units>();
        }

        [JsonProperty(Order = -3)]
        public string id { get; set; }

        [JsonProperty(Order = -3)]
        public string company { get; set; }

        [JsonProperty(Order = -3)]
        public string tenant { get; set; }

        [JsonProperty(Order = -2)]
        public virtual ICollection<units> units { get; set; }

        public virtual shippingInfo shippingInfo { get; set; }
        public virtual status_tk status_tk { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
    }
}
