//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class RootObject
    {
        [JsonIgnore]
        public int id { get; set; }

        [JsonIgnore]
        public string message_id { get; set; }

        [JsonProperty(Order = 2)]
        public string webhook_id { get; set; }

        [JsonProperty(Order = 2)]
        public string transaction_id { get; set; }

        [JsonProperty(Order = 2)]
        public long timestamp { get; set; }

        [JsonProperty(Order = 2)]
        public string subject { get; set; }

        [JsonProperty(Order = -2)]
        public string sender { get; set; }

        [JsonProperty(Order = 2)]
        public int retries { get; set; }

        [JsonProperty(Order = 2)]
        public string reference { get; set; }

        [JsonProperty(Order = 2)]
        public string @namespace { get; set; }

        [JsonProperty(Order = 2)]

        public virtual body body { get; set; }
    }
}
