//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class status_tk
    {   
        [JsonIgnore]
        public int id { get; set; }

        [JsonIgnore]
        public string message_id { get; set; }

        [JsonProperty(Order = -2)]
        public string status { get; set; }
    
        public virtual message message { get; set; }
    }
}
